### ISSUE TITLE
Not compatible with Flask >= 1.0

### ISSUE THREAD

**Issue by sebastiendarocha** [borgbackup/borgweb#116]
Hello,

When I launch borgweb with a fresh  install, I run into this problem:
```
(borg-env) 11:16 seba@seba-N750HU: ~/Sources/borg-env$ bin/borgweb 
Traceback (most recent call last):
  File "bin/borgweb", line 11, in <module>
    load_entry_point('borgweb', 'console_scripts', 'borgweb')()
  File "/home/seba/Sources/borg-env/borgweb/borgweb/app.py", line 29, in main
    application = create_app()
  File "/home/seba/Sources/borg-env/borgweb/borgweb/app.py", line 23, in create_app
    app.error_handler_spec[None][404] = err404
KeyError: None
```
I've made it work by doing this:
```
(borg-env) 11:20 seba@seba-N750HU: ~/Sources/borg-env/borgweb$ git diff
diff --git a/setup.py b/setup.py
index 080c906..b81a5ed 100644
--- a/setup.py
+++ b/setup.py
@@ -56,6 +56,6 @@ setup(
     },
     setup_requires=['setuptools_scm>=1.7'],
     install_requires=[
-        'flask',
+        'flask<1.0.0',
     ],
 )
```
Then it works. If you don't have time to migrate to Flask 1.0.0, I can make a PR with this modification if you want :-)

**Comment by ThomasWaldmann** [comment]
http://flask.pocoo.org/docs/1.0/upgrading/

strange, I don't see anything special there for 1.0.x.

**Comment by ThomasWaldmann** [comment]
temporarily worked around by requiring flask < 1.0, see #119.
