### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration - when starting on Ubuntu 20.04 with python3 

### ISSUE THREAD

**Issue by MurzNN** [borgbackup/borgweb#134]
I try to use borgweb on my Ubuntu 20.04 with python3, installs via this command:
```
pip3 install burp-ui
...
Successfully installed Babel-2.8.0 Flask-0.12.4 Flask-Babel-0.11.2 Flask-Bower-1.3.0 Flask-Caching-1.4.0 Flask-Login-0.4.1 Flask-WTF-0.14.2 WTForms-2.1 aniso8601-8.0.0 arrow-0.13.0 backports.functools-lru-cache-1.2.1 burp-ui-0.6.6 cffi-1.14.2 click-7.1.2 flask-restplus-0.10.1 itsdangerous-1.1.0 pluginbase-0.5 pyOpenSSL-19.1.0 pyasn1-0.4.8 pycparser-2.20 six-1.11.0 tzlocal-1.5.1 werkzeug-0.14.1
```
And after this - I have error when try to start the program:
```
# burp-ui -- -h 0.0.0.0 -p 8080
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/burpui/server.py", line 479, in load_modules
    self.client = Client(self, conf=self.conf)
  File "/usr/local/lib/python3.8/dist-packages/burpui/misc/backend/burp2.py", line 137, in __init__
    self.parser = Parser(self)
  File "/usr/local/lib/python3.8/dist-packages/burpui/misc/parser/burp1.py", line 57, in __init__
    self._load_all_conf()
  File "/usr/local/lib/python3.8/dist-packages/burpui/misc/parser/burp1.py", line 154, in _load_all_conf
    self._load_conf_srv()
  File "/usr/local/lib/python3.8/dist-packages/burpui/misc/parser/burp1.py", line 104, in _load_conf_srv
    self.clientconfdir = self._server_conf.get('clientconfdir')
  File "/usr/local/lib/python3.8/dist-packages/burpui/misc/parser/utils.py", line 1638, in get
    return self._get(key, default)
  File "/usr/local/lib/python3.8/dist-packages/burpui/misc/parser/utils.py", line 1619, in _get
    self._refresh()
  File "/usr/local/lib/python3.8/dist-packages/burpui/misc/parser/utils.py", line 1601, in _refresh
    for key in viewkeys(self.types):
RuntimeError: dictionary keys changed during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/burpui/cli.py", line 49, in <module>
    app = create_app(
  File "/usr/local/lib/python3.8/dist-packages/burpui/app.py", line 170, in create_app
    app.setup(app.config['CFG'], unittest, cli)
  File "/usr/local/lib/python3.8/dist-packages/burpui/server.py", line 413, in setup
    self.load_modules()
  File "/usr/local/lib/python3.8/dist-packages/burpui/server.py", line 490, in load_modules
    raise Exception(msg)
Exception: Failed loading backend for Burp version 2: dictionary keys changed during iteration
```

How can I solve this problem?

**Comment by MurzNN** [comment]
Sorry, wrong repo, this is for burp-ui project
